### ISSUE TITLE
CBMailservices Exception if Email Contains Binary Attachment

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/cbmailservices#26]
I discovered an issue when playing around with the cbmailservices if an email has a binary attachment and the email fails validation, it will throw an exception via LogBox because Logbox can't handle binary data.  

_JSON serialization failure: Unable to serialize binary data to JSON._
```
coldbox\system\logging\LogEvent.cfc:82
coldbox\system\logging\appenders\ConsoleAppender.cfc:50
coldbox\system\logging\Logger.cfc:399
coldbox\system\logging\Logger.cfc:301
modules\cbmailservices\models\MailService.cfc:272
```

I'm not sure if Logbox will ever be able to handle binary data, so it might be a good idea to strip anything binary from `mailParams` as a precaution, just to be safe.  

Here's how you can replicate the issue:
```
var email = mailService.newMail( 
    to = "", // intentionally blank
    from = "me@mydomain.com",
    subject = "All Your Base Are Belong to Us",
    type = "html",
    body = "<p>Hello</p>
);

email.addMailParam(
    file = "my-document.pdf",
    content = toBinary( base64PdfFile ), 
    type = "application/pdf"
);

mailService.send( email );
```

**Comment by michaelborn** [comment]
I'm going to close this as resolved by #27 . Great work @homestar9 !
